- name: Ensure Prometheus is installed
  apt:
    name: prometheus
    state: present
    update_cache: yes

- name: Ensure Prometheus service is enabled and running
  service:
    name: prometheus
    state: started
    enabled: yes

- name: Deploy Prometheus configuration
  copy:
    content: |
      global:
        scrape_interval: 15s
        evaluation_interval: 15s

      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets:
              {% for host in groups['monitoring'] %}
              - '{{ host }}:9090'
              {% endfor %}
            
        - job_name: "node_exporter"
          static_configs:
            - targets:
              {% for host in groups['exporters'] %}
              - '{{ host }}:9100'
              {% endfor %}
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0644'
  notify: Restart Prometheus

- name: Ensure Prometheus is listening on port 9090
  wait_for:
    port: 9090
    timeout: 10


